name: flutter_file_store
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.0
  path_provider: ^1.6.24
  sqflite: ^1.3.1+2
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  flutter_bcrypt: ^1.0.5
  image_picker: ^0.6.7+14
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
